services:
  frontend-app:
    image: ${APP_IMAGE:-}
    container_name: frontend

  nginx-anycors:
    image: nginx:latest
    container_name: nginx-anycors
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      backend-app:
        condition: service_healthy
      frontend-app:
        condition: service_started

  backend-app:
    image: dev/oxb4f/backend:${TAG_BACKEND}
    container_name: backend
    command: sh -c 'bun migrate:db && bun dev'
    restart: always
    env_file:
      - ${ENV_FILE:-.env.backend}
    ports:
      - 8080:8080
    depends_on:
      backend-db:
        condition: service_healthy
      backend-minio:
        condition: service_healthy
      backend-elasticsearch:
        condition: service_healthy
    expose:
      - "8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- 'http://localhost:8080/ping?ping=pong'"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend-db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    expose:
      - "5432"
    command: -p "5432"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
      - POSTGRES_HOST=backend-db
      - POSTGRES_PORT=5432
    volumes:
      - ./etc/db/dumpfile.sql:/docker-entrypoint-initdb.d/dumpfile.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app -p 5432 -h backend-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend-minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
    expose:
      - "9000"
      - "127.0.0.1:9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=password12345
    volumes:
      - ~/minio/data:/data
    healthcheck:
      test: ["CMD-SHELL", "mc alias set dev http://backend-minio:9000 minio password12345"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend-createbuckets:
    image: minio/mc:latest
    depends_on:
      backend-minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add dev http://backend-minio:9000 minio password12345;
      /usr/bin/mc mb dev/bucket;
      /usr/bin/mc policy download dev/bucket;
      exit 0;
      "

  backend-elasticsearch:
    image: elasticsearch:9.0.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-changeme}
      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - logger.level=INFO
    ports:
      - "${ELASTICSEARCH_PORT:-9200}:9200"
    expose:
      - "${ELASTICSEARCH_PORT:-9200}"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://backend-elasticsearch:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          memory: 256M
    profiles:
      - dev
      - elastic
    init: true

volumes:
  elasticsearch_data:
    name: ${APP_NAME:-backend}-elasticsearch-data