services:
  frontend-app:
    image: ${APP_IMAGE:-}
    container_name: frontend

  nginx-anycors:
    image: nginx:latest
    container_name: nginx-anycors
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      backend-app:
        condition: service_healthy
      frontend-app:
        condition: service_started

  backend-app:
    image: dev/oxb4f/backend:${TAG_BACKEND}
    container_name: backend
    command: sh -c 'bun migrate:db && bun dev'
    restart: always
    env_file:
      - ${ENV_FILE:-.env.backend}
    ports:
      - 8080:8080
    depends_on:
      backend-db:
        condition: service_healthy
      backend-minio:
        condition: service_healthy
    expose:
      - "8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O- 'http://localhost:8080/ping?ping=pong'"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend-db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    expose:
      - "5432"
    command: -p "5432"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
      - POSTGRES_HOST=backend-db
      - POSTGRES_PORT=5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app -p 5432 -h backend-db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend-minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
    expose:
      - "9000"
      - "127.0.0.1:9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=password12345
    volumes:
      - ./docker/minio/data:/data
    healthcheck:
      test: ["CMD-SHELL", "mc alias set dev http://backend-minio:9000 minio password12345"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend-createbuckets:
    image: minio/mc:latest
    depends_on:
      backend-minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add dev http://backend-minio:9000 minio password12345;
      /usr/bin/mc rm -r --force dev/bucket;
      /usr/bin/mc mb dev/bucket;
      /usr/bin/mc policy download dev/bucket;
      exit 0;
      "