services:
  frontend-app:
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
    command: ["npm", "run", "dev", "--", "--host"]
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
          ignore:
            - ./node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    profiles:
      - dev
