export const BOOK_GENRES = [
	"Mystery & Thriller",
	"Romance",
	"Science Fiction",
	"Fantasy",
	"Horror",
	"Literary Fiction",
	"Historical Fiction",
	"Adventure",
	"Crime & Detective",
	"Young Adult",
	"Children's Books",
	"Contemporary Fiction",
	"Dystopian",
	"Magical Realism",
	"Western",
	"Action & Suspense",
	"Humor & Comedy",
	"Drama",
	"Classic Literature",
	"Biography & Autobiography",
	"History",
	"Science & Nature",
	"Health & Fitness",
	"Self-Help & Personal Development",
	"Business & Economics",
	"Politics & Government",
	"Philosophy",
	"Religion & Spirituality",
	"Travel",
	"Cooking & Food",
	"Art & Design",
	"Education & Teaching",
	"Technology & Computing",
	"Psychology",
	"Sociology",
	"True Crime",
	"Sports & Recreation",
	"Parenting & Family",
	"Reference",
	"Essays",
	"Memoir",
	"Poetry",
	"Drama & Plays",
	"Short Stories",
	"Graphic Novels & Comics",
	"Academic & Textbooks",
	"Professional & Technical",
] as const;

export const API_REFERENCE = {
	bookGenres: BOOK_GENRES,
} as const;
